#!/usr/bin/env node
// Reads web/dist/ (excluding book.bin) and writes src/server/embedded-assets.gen.ts
// with all assets base64-encoded for the SEA binary build.
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join, relative, extname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const root = join(__dirname, '..')
const distDir = join(root, 'web', 'dist')
const outFile = join(root, 'src', 'server', 'embedded-assets.gen.ts')

const EXCLUDE = new Set(['book.bin'])

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true })
  const files = []
  for (const e of entries) {
    const full = join(dir, e.name)
    if (e.isDirectory()) files.push(...await walk(full))
    else files.push(full)
  }
  return files
}

const files = await walk(distDir)
const lines = []
let totalBytes = 0

for (const file of files) {
  const rel = relative(distDir, file).replace(/\\/g, '/')
  if (EXCLUDE.has(rel.split('/').pop())) continue
  const buf = await readFile(file)
  totalBytes += buf.length
  lines.push(`  '${rel}': '${buf.toString('base64')}'`)
}

const code = `// AUTO-GENERATED by scripts/generate-assets.mjs — do not edit manually
export const ASSETS: Record<string, string> = {
${lines.join(',\n')},
}
`

await writeFile(outFile, code)
console.log(`Generated ${outFile}: ${lines.length} files, ${(totalBytes / 1024 / 1024).toFixed(1)} MB`)
